// an array of BoJack Horseman Quotes
export const quotes = [
  "Secretariat: “Before I Leaped, I Should Have Seen The View From Halfway Down.”",
  "Todd: “You Turn Yourself Around. That’s What It’s All About.”",
  "BoJack: “Life’s a b*tch and then you die, right? \n Diane: Sometimes life’s a b*tch and then you keep living.”",
  "BoJack: “I feel like my life is just a series of unrelated wacky adventures.”",
  "Diane: “That’s the problem. Because he’s so nice, people don’t want to think he’s capable of awful things, so they let him off the hook.”",
  "BoJack: “I need you to tell me that I’m a good person. I know that I can be selfish and narcissistic and self-destructive, but underneath all that, deep down, I’m a good person, and I need you to tell me that I’m good. Diane? Tell me, please, Diane. Tell me that I’m good.”",
  "BoJack: “He’s so stupid, he doesn’t realize how miserable he should be.”",
  "Wanda Pierce: “When you look at someone through rose-colored glasses, all the red flags just look like flags.”",
  "Jogging Baboon: “It gets easier. Every day, it gets a little easier. But you gotta do it every day – that’s the hard part. But it does get easier.”",
  "BoJack: “I need to go take a shower so I can’t tell if I’m crying or not.”",
  "BoJack: “I’m Responsible For My Own Happiness? I Can’t Even Be Responsible For My Own Breakfast!”",
  "BoJack: “This is a situation comedy. No one watches the show to feel feelings. Life is depressing enough already.”",
  "BoJack: “I Am In Pain, All The Time. My Whole Life. And You Have No Idea.”",
  "BoJack: “Not Understanding That You’re A Horrible Person Doesn’t Make You Less Of A Horrible Person.”",
  "Diane: “Every Happy Ending Has The Day After The Happy Ending.”",
  "BoJack: “Sometimes I Think I Was Born With A Leak, And Any Goodness I Started With Just Slowly Spilled Out Of Me And Now It's All Gone. And I'll Never Get It Back In Me. It's Too Late. Life Is A Series Of Closing Doors, Isn't It?”",
  "Hollyhock: “That voice, the one that tells you you’re stupid, worthless, and ugly… it goes away right? It’s just a dumb teenage girl thing, but… then it goes away?”\nBoJack: “Yeah”",
  "BoJack: “I Want To Feel Good About Myself. The Way You Do. And I Don't Know How. I Don't Know If I Can.”",
  "Todd: “You Can't Keep Doing S**Tty Things, And Then Feel Bad About Yourself Like That Makes It Okay! YOU NEED TO BE BETTER!”",
  "Beatrice Horseman: “You were born broken. That’s your birthright. And now you can fill your life with projects — your books, and your movies, and your little girlfriends but that won’t make you whole. You’re BoJack Horseman. There’s no cure for that.”",
  "Diane: “Why Can't I Be Happy? Am I Busted? I Am. I'm A Pit! I'm A Pit That Good Things Fall Into!”",
  "BoJack: “Settle. Because otherwise you’re just gonna get older and harder, and more alone. And you’re gonna do everything you can to fill that hole, with friends, and your career, and meaningless sex, but the hole doesn’t get filled. One day, you’re gonna look around and you’re going to realize that everybody loves you, but nobody likes you. And that is the loneliest feeling in the world.”",
  "BoJack: “Sarah Lynn? Sarah Lynn?“",
  "BoJack: “I've Had A Lot Of What I Thought Were Rock Bottoms, Only To Discover Another, Rockier Bottom Underneath.“",
  "Mr. Peanutbutter: “The universe is a cruel, uncaring void. The key to being happy isn’t the search for meaning; it’s just to keep yourself busy with unimportant nonsense, and eventually, you’ll be dead.”",
  "Henry Winkler: “There is no shame in dying for nothing. That’s why most people die.”",
  "BoJack: “Look, for a lot of people, life is just one long hard kick in the urethra.”",
  "Secretariat: “When you get sad you run ,straight ahead and you keep running forward no matter what there are people in your life that who are going to try to hold you back , slow you down , but you don’t let them. Don’t you ever stop running, don’t ever look behind you there is nothing for you behind you. All that exists is whats ahead.”",
  "BoJack:  “I can’t say no to people because I want everyone to like me.”",
  "Todd: “Things don’t become traditions because they’re good, BoJack, they become good because they’re traditions.”",
  "BoJack: “Closure is a made up thing by Steven Spielberg to sell movie tickets. It, like true love and the Munich Olympics, doesn’t exist in the real world.”",
  "BoJack: “We’re just two lonely people trying to hate ourselves a little less.”",
  "BoJack: “Kelsey, in this terrifying world, all we have are the connections that we make. I’m sorry I got you fired, I’m sorry I never called you after.”",
  "Diane Nguyen: “It’s not about being happy, that is the thing. I’m just trying to get through each day. I can’t keep asking myself ‘Am I happy? ‘ It just makes me more miserable. I don’t know If I believe in it, real lasting happiness, All those perky, well-adjusted people you see in movies and TV shows ? I don’t think they exist.”",
  "BoJack: “Why 12 steps? Nobody wants to do 12 of anything. Did you see ’12 Years A Slave’ and think ‘that’s a short number of years to be a slave?'”",
  "BoJack: “I want to do things with you. Fully clothed, sober, in daylight hours.”",
  "BoJack: “Why put the skip ad button so late? I’m not skipping now. I’m invested.”",
  "BoJack: “I drove, but I moved my arm a bunch so the Fitbit counted the miles.”",
  "BoJack: “Also, are you wearing comfortable shoes? Because I feel like that was a long road to walk to get to that punchline.”",
  "BoJack: “Slap my salami, the guy’s a commie.”",
  "BoJack: “I spend a lot of time with the real me and believe me, nobody’s gonna love that guy.”",
];
